version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.22
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mqtt-broker


#  typescript:
#    build:
#      context: ./typescript-app
#    depends_on:
#      - influxdb
#    ports:
#      - "8080:80"
#    environment:
#      - INFLUX_URL=https://us-west-2-1.aws.cloud2.influxdata.com
#      - INFLUX_TOKEN=6b0bd7cfadba46e46c53747166365971
#      - INFLUX_ORG=school
#      - INFLUX_BUCKET=telegraf
#    volumes:
#      - ./typescript-app/dist:/usr/share/nginx/html
#      - ./typescript-app/nginx.conf:/etc/nginx/nginx.conf:ro


  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


volumes:
  influxdb-storage:
