version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.22
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mqtt-broker

  fast_api:
    image: fast_api
    build:
      context: ./fast_api
    ports:
      - "5000:5000"
    depends_on:
      - influxdb

  # vue_app:
  #   image: vue_app
  #   build:
  #     context: ./vue_app
  #   volumes:
  #     - ./vue_app:/home/node/vueapp
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - fast_api
  #   command: npm run dev
  vue_app:
    image: vue_app
    build:
      context: ./vue_app
    ports:
      - "8080:8080"
    depends_on:
      - fast_api
    command: npm run dev
    working_dir: /home/node/vueapp  # Add this line to set the working directory


  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


volumes:
  influxdb-storage:
